# Generated by Django 2.2 on 2019-05-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254)),
                ('ucontact', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('U', 'User')], max_length=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
